name: LobbyKeep
author: 615283
description: Stops people falling into the void.
version: ${project.version}
main: com.georlegacy.general.lobbykeep.LobbyKeep
commands:
  pkcreate:
    usage: /<command> <name> <startX> <startY> <startZ> <endX> <endY> <endZ>
    permission: lobbykeep.parkour.create
    description: Creates a new parkour route
  lkreload:
    usage: /<command>
    permission: lobbykeep.reload
    description: Relaods the config(s)

permissions:
  lobbykeep.parkour.create:
    default: op
  lobbykeep.reload:
    default: op