name: LobbyKeep
author: 615283
description: Plugin for server lobbies.
version: ${project.version}
main: com.georlegacy.general.lobbykeep.LobbyKeep
commands:
  pkcreate:
    usage: /<command> <name> <startX> <startY> <startZ> <endX> <endY> <endZ>
    permission: lobbykeep.parkour.create
    description: Creates a new parkour route
  pktop:
    usage: /<command> <parkourname>
    permission: lobbykeep.parkour.top
    description: Lists the best times for the parkour
  pklist:
    usage: /<command>
    permission: lobbykeep.parkour.list
    description: Lists all parkour routes
  pkstart:
    usage: /<command> <parkourname>
    permission: lobbykeep.parkour.start
    description: Starts a parkour route
  lkreload:
    usage: /<command>
    permission: lobbykeep.reload
    description: Reloads the config(s)

permissions:
  lobbykeep.parkour.create:
    default: op
  lobbykeep.parkour.top:
    default: true
  lobbykeep.parkour.list:
    default: true
  lobbykeep.parkour.start:
    default: true
  lobbykeep.reload:
    default: op